db:
  image: postgres

data:
  image: cogniteev/echo
  volumes:
    - /var/www/assets

uwsgi:
  restart: always
  image: vanessa/expfactory
  volumes_from:
    - data
  volumes:
    - .:/code
    - ./static:/var/www/static
  links:
    - redis
    - db

nginx:
  restart: always
  image: nginx
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./compose/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    - ./uwsgi_params.par:/etc/nginx/uwsgi_params.par:ro
  volumes_from:
    - uwsgi
    - data
  links:
    - uwsgi
    - db

redis:
  restart: always
  image: redis

worker:
  image: vanessa/expfactory
  command: celery worker -A expdj.celery -Q default -n default@%h
  volumes:
    - .:/code
  volumes_from:
    - uwsgi
    - data
  links:
    - redis
    - db
