uwsgi:
  build: ./
  command: python ./manage.py runserver 0.0.0.0:8000
  ports:
    - "8000:8000"

worker:
  build: ./

nginx:
  image: nginx
  volumes:
    - ./compose/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
